### ISSUE TITLE
synchrotron-self-absorption in SSC

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#1]
The current code applies the SSA only when the sed_flux is computed of synchrotron radiation, but non-absorbed synchrotron emission is used for the calculation of the IC photons from SSC, while it should be done consistently also with SSA taken into account

**Comment by cosimoNigro** [comment]
Thanks @jsitarek, with PR #3 I fixed this.
Now you can choose whether or not to take into account the self absorption directly when initialising the `Synchrotron` object, by passing the `ssa` optional argument (default is `False`)
```python
synch_ssa = Synchrotron(blob, ssa=True)
```
This allow to consider directly the attenuated spectrum in the SSC computation.
See the updated [documentation page](https://agnpy.readthedocs.io/en/latest/synchrotron.html) and [notebook tutorial](https://github.com/cosimoNigro/agnpy/blob/master/tutorials/synchrotron_self_compton.ipynb).

Let me know if I can close this issue.
I updated this changes to `pip`.

**Comment by jsitarek** [comment]
Thanks @cosimoNigro ! I'm getting some divisions by 0 and a few other warnings in Python 3.6.9 (see attached notebook, I had to rename it to .txt to attach it here, strange), but either way it seems to work fine, thanks. 
[synchrotron_self_compton_js.ipynb.txt](https://github.com/cosimoNigro/agnpy/files/4267157/synchrotron_self_compton_js.ipynb.txt)

**Comment by cosimoNigro** [comment]
Hey @jsitarek, since they appear to be warning due to numerics and no major problem is encountered I am closing this issue.
