### ISSUE TITLE
 EC - check of peak flux

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#13]
In https://github.com/jsitarek/agnpy/blob/master/tests/basic/simple_ec.ipynb I put a few tests of the EC code comparing it with back of the envelope calculations.

in [16] (test2) compares the flux of the EC spectrum for Thomson case without beaming

in [23] (test3) there is the same check done in K-N regime (still without beaming)

in [27] (test4) the same is done for Thomson regime but with strong beaming,

in all the 3 cases the obtained flux is about a factor 2 lower than what I would expect from the back on the envelope calculations

**Comment by cosimoNigro** [comment]
Can we close this? It's been a while since we get a good agreement for all the EC cases...
