### ISSUE TITLE
Error in the EBL absorption

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#134]
@pawel21 saw that the EBL absorption is a suspiciously low energy (~3 orders of magnitude too low):
https://agnpy.readthedocs.io/en/latest/absorption.html#extragalactic-background-light

The code that is loading the EBL models says that the energies are in eV:
https://github.com/cosimoNigro/agnpy/blob/075933ef582f2d90ec4572b00d65e8b9b1335577/agnpy/absorption/absorption.py#L785
however looking e.g. in ebl_dominguez11.fits the values go from 1.e6 to 1.e11, which would more like keV:
![Zrzut ekranu z 2023-02-01 10-04-53](https://user-images.githubusercontent.com/33022433/215919820-fc201caa-b079-471e-98df-0bef5c68e197.png)
![Zrzut ekranu z 2023-02-01 10-04-31](https://user-images.githubusercontent.com/33022433/215919824-62a31430-c299-4a5b-8339-33ab48cc3fc6.png)
![Zrzut ekranu z 2023-02-01 10-04-24](https://user-images.githubusercontent.com/33022433/215919826-b8750924-a1f7-4053-954a-6522288ba7a0.png)

@cosimoNigro how were the fits files with the models generated?

**Comment by cosimoNigro** [comment]
Hi @jsitarek,

it was a very stupid mistake from my side.
I assigned eV units to the energies, while I should have assigned keV (it is the format of the XSPEC tables).

Will fix it soon in a PR.
