### ISSUE TITLE
Issue with fitting MWL SED using agnpy

### ISSUE THREAD

**Issue by maitreyakun** [cosimoNigro/agnpy#140]
My goal is to fit a MWL SED using agnpy. As per [given documentation](https://agnpy.readthedocs.io/en/latest/tutorials/ssc_sherpa_fit.html), I try to fit the SED Data with `agnpy.fit`. However, it seems that `agnpy` cannot import the `SycnhrotronSelfComptonModel`, which is essential to the fit. Upon running: 
`from agnpy.fit import SynchrotronSelfComptonModel, load_sherpa_flux_points` 
it returns: 
`ImportError: cannot import name 'SynchrotronSelfComptonModel' from 'agnpy.fit' (/home/anirban/mambaforge/lib/python3.9/site-packages/agnpy/fit/__init__.py)` 

How can this be resolved?

**Comment by maitreyakun** [comment]
Thanks, I shall try uninstalling and installing it again (the latest version), and see if that fixes this issue.

**Comment by MagXXG** [comment]
Hi, @mai

> Thanks, I shall try uninstalling and installing it again (the latest version), and see if that fixes this issue.

Hi, excuse me , I would like to know if this problem is solved by re-installating packages, cause I had the same problem as you .

**Comment by cosimoNigro** [comment]
@maitreyakun, @MagXXG do you have sherpa and Gammapy installed (see here)[https://agnpy.readthedocs.io/en/latest/fit.html#prerequisites].

It would help to know the OS you are using, the python and `agnpy` version.

**Comment by MagXXG** [comment]
> @maitreyakun, @MagXXG do you have sherpa and Gammapy installed [see here](https://agnpy.readthedocs.io/en/latest/fit.html#prerequisites)?
> 
> It would help to know the OS you are using, the `python` and `agnpy` versions, and how did you install `agnpy`. Thanks.

Ah, yes.  because my system is Win11——that's why I cannot install and use the Sherpa, so there is such a mistake! Thanks a lot!

**Comment by maitreyakun** [comment]
> @maitreyakun, @MagXXG do you have sherpa and Gammapy installed [see here](https://agnpy.readthedocs.io/en/latest/fit.html#prerequisites)?
> 
> It would help to know the OS you are using, the `python` and `agnpy` versions, and how did you install `agnpy`. Thanks.

Thanks a lot. It turned out that I had ```gamma``` installed, but not ```sherpa```. After installing, I was able to perform the fit on one sample SED (Mrk 421) fine.

**Comment by cosimoNigro** [comment]
Looks like this issue was solved by upgrading the installation of the dependencies.
