### ISSUE TITLE
Crosscheck of SSC radiation

### ISSUE THREAD

**Issue by cosimoNigro** [cosimoNigro/agnpy#17]
We should try to crosscheck with different approaches the Synchrotron Self Compton radiation:

- [x] **crosscheck against the literature**;
- [x] **crosscheck against another code**;
- [ ] **crosscheck against back-of-the-envelope calculation**.

Each of the tick box will be marked once the crosscheck is obtained.
After all of them are marked we will close the issue, and be sure that the SSC computation is reliable.

**Comment by cosimoNigro** [comment]
the crosscheck against the literature is provided in the tutorial notebook.
https://agnpy.readthedocs.io/en/latest/tutorials/synchrotron_self_compton.html
So I am checking that box.

**Comment by cosimoNigro** [comment]
The crosscheck against another code is provided in this notebook:
https://github.com/cosimoNigro/agnpy/blob/master/tests/crosschecks/jetset_ssc_xcheck.ipynb
I am checking the corresponding box.

**Comment by cosimoNigro** [comment]
As for the **crosscheck against back-of-the-envelope calculation** @jsitarek has a notebook doing this in his fork, will check the box once the notebook is added.

**Comment by jsitarek** [comment]
If you mean this one:
https://github.com/cosimoNigro/agnpy/blob/master/tests/basic/test_gmax.py
it is already in the upstream branch.
The cross check consists of:
- computing the synchrotron energy density with an independent function that is merged into the emission_region.py 
- converting the synchrotron energy  density into energy flux and comparing with the simulated one
- integrating the simulated SSC energy flux and comparing with simulated synchrotron flux to check if the same energy density of magnetic field and soft photons provides the same energy flux.

All calculations are done in Thomson regime and with no beaming. Also the spectral shapes are not checked (but with the other two tests of SSC I guess it is enough). 

The macro is however a .py macro (and a bit mixed in with the checks of the gamma break and gamma max functions) and not a notebook (I produced a notebook earlier, when some parts of the code were not yet in the upstream branch so it is easy for you to check the results). I can reextract the relevant parts of the macro into a notebook and commit it.

**Comment by cosimoNigro** [comment]
Oh right, it's in that notebook.
No leave it to me, I wanted to reorganise the tests in a set of macros that can be run each time we change the code. Thanks, this is almost done by the way.

**Comment by cosimoNigro** [comment]
I think the introduction of the test suite addresses the pending checks in this issue.
We have now a crosscheck against the literature (Dermer 2009)

![synch_comparison_figure_7_4_dermer_menon_2009](https://user-images.githubusercontent.com/26409711/95345744-5bfac600-08bb-11eb-8637-a9ef2cd4d01f.png)

and more crosschecks against another code, specifically crosschecks on the synchrotron self-absorption, against JetSet
![ssa_pwl_comparison_jetset_1 1 2](https://user-images.githubusercontent.com/26409711/95346229-e2afa300-08bb-11eb-9c87-f96184bcd296.png)
![ssa_bpwl_comparison_jetset_1 1 2](https://user-images.githubusercontent.com/26409711/95346217-e0e5df80-08bb-11eb-986e-5f3f8d51e072.png)
![ssa_lp_comparison_jetset_1 1 2](https://user-images.githubusercontent.com/26409711/95346222-e2170c80-08bb-11eb-894d-6f48cdc9c11c.png)

I do not think the test agains the back of the envelope calculation is needed, these tests are quite robust and I think we are safe that the synchrotron calculation of agnpy is correct.
