### ISSUE TITLE
Normalization for spectral index -2

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#2]
In the case of spectral index exactly equal to -2 the analytical normalization function results in division by zero. Either a dedicated analytical integral should be used in this case, or a simple fix it to substitute automatically -2 by a very close number e.g. -2.001

**Comment by cosimoNigro** [comment]
Thanks @jsitarek, with PR #3 I fixed this.
Now you can choose whether or not to take into account the self absorption directly when initialising the `Synchrotron` object, by passing the `ssa` optional argument (default is `False`)
```python
synch_ssa = Synchrotron(blob, ssa=True)
```
This allow to consider directly the attenuated spectrum in the SSC computation.
See the updated [documentation page](https://agnpy.readthedocs.io/en/latest/synchrotron.html) and [notebook tutorial](https://github.com/cosimoNigro/agnpy/blob/master/tutorials/synchrotron_self_compton.ipynb).

Let me know if I can close this issue.

**Comment by jsitarek** [comment]
Thanks @cosimoNigro and sorry for late reply. It works perfectly way
