### ISSUE TITLE
Move the constraints on the lorentz factors in another class

### ISSUE THREAD

**Issue by cosimoNigro** [cosimoNigro/agnpy#42]
The `emission_region` class is getting too long, we should consider moving the constraint on the maximum and break Lorentz factors in a new class.
This class should have the objective of returning a constraint on the physical parameters, how should we call it @jsitarek?

**Comment by jsitarek** [comment]
it will complicate the API somewhat, because you would still need to pass the blob to this class, but I can do it if you want. 

I'm also wondering about the name maybe "spectral_constraints" or "consistency_constraints" or simply "cooling", any preference?

**Comment by jsitarek** [comment]
since the topic got cold, let me then propose to use the first option on the list:
spectral_constraints
I can do the changes in mid September, so if you prefer a different name please let me know till the end of the next week.

**Comment by cosimoNigro** [comment]
Solved by #44, thanks @jsitarek.
