### ISSUE TITLE
agnpy poster at ADASS XXX

### ISSUE THREAD

**Issue by cosimoNigro** [cosimoNigro/agnpy#51]
Dear @jsitarek, @pawel21, @mwcraig,

I will be presenting `agnpy` at the [ADASS XXX](https://adass2020.es/) with a poster.
You can find it [at this link](https://www.overleaf.com/3554278186qjdsbsbbvnxj).

Let me know if you have any comment. 
Small edits can be directly implemented in the overleaf, for major changes please leave a comment.
I listed all the contributors (i.e. the four of us) as authors.

Thanks

**Comment by mwcraig** [comment]
Looks good, thanks! I changed the astropy citation to the most recent astropy paper from 2018.

**Comment by jsitarek** [comment]
Hi Cosimo, 

Thanks a lot for preparing it. It will give a tentative reference for the projects using it. 
I made some comments (look for # JS: in the overleaf, there are 8 comments there), but they are just suggestions.

**Comment by cosimoNigro** [comment]
Thanks for the comments Julian, I have implemented some of them.

> It will give a tentative reference for the projects using it.

Actually I am not submitting an abstract. I have another presentation at this conference and also the MAGIC meeting in the same week, so I simply could not manage to write also the abstract for agnpy (they are not mandatory).

On the other hand this month I will start to draft the agnpy paper.
In my view for the development of the code, the only features missing to attempt a publication are the crosscheck of the optical depth (that we are already doing) and a fitting procedure.
I am actually implementing more general functions for fitting, you'll see in one of my next PRs.

So, I hope that by next year we have a proper paper reference.

**Comment by cosimoNigro** [comment]
Today is the last day of the conference, so I am closing the issue. 
Thanks for the feedback.
