### ISSUE TITLE
SmoothlyBrokenPowerLaw normalization

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#6]
SBPL normalization from energy density does not work (it gives an error because of wrong units).

BTW, according to the definition in the code, SmoothlyBrokenPowerLaw is not "smoothly" broken, there is a sharp break at gamma_b

**Comment by cosimoNigro** [comment]
Thanks,

was this solved by PR #8?

**Comment by jsitarek** [comment]
Hi, I confirm that the problem was solved, and also the name of the spectral deifnition now looks more consistent. Still I'm wondering if it is useful to keep both BrokenPowerLaw and BrokenPowerLaw2. They only differ by definition of k_e and except of this when e.g. initialized with normalization to (energy) density they will provide exactly the same results. The only different is k_e, but if you keep the original BrokenPowerLaw, one can also normalize it to k_e at gamma=1 with those new functions.
