### ISSUE TITLE
Providing a fit tutorial for a BL Lac SED

### ISSUE THREAD

**Issue by cosimoNigro** [cosimoNigro/agnpy#68]
We decided not to include any fit wrapper in the code but to simply show in a couple of tutorial notebooks how to implement one using `sherpa`. Sherpa has several minimisation routines and data handling utilities.
We should have a working example with Synchrotron + SSC for a BL Lac, I started it in [this notebook](https://github.com/cosimoNigro/agnpy/blob/master/experiments/basic/sherpa_fitting_ssc_trial.ipynb) using the famous 2011 MWL observations of Mrk421.

The fit is not converging and it has to be fixed.

**Comment by jsitarek** [comment]
I'm working on making the one for FSRQ EC fit and going through this example for SSC fit of Mrk I realized that  you are not using SSA in the synchrotron fit. Even while it does not change the result in this particular case (see the figure below ) and makes the fiting procedure probably a tiny bit faster, for such an example I think it would be best to include explicit SSA by " ssa=True" in the calc function
![ssa_in_ssc_fit](https://user-images.githubusercontent.com/33022433/103887374-3ad88a00-50e3-11eb-8c86-212afce0d21b.png)

**Comment by cosimoNigro** [comment]
Hi @jsitarek yesterday finally managed to get the fit converging with sherpa. The trick was to define the function to be minimised with the logarithm of the parameters that vary over several orders of magnitude (e.g. normalisation, Lorentz factors of the electron distribution `k_e`, `gamma_0`). Only fitting the parameters of the LogParabola electron distribution (minimum and maximum Lorentz factor fixed though) takes only ~7 sec!
Check []().
Of course the fit can be improved in several ways, using a different minimiser from sherpa (e.g. MC minimisation) or including secondary effects like SSA. I am keeping this issue open until when we are completely satisfied with the Mrk 421 SED fit.

**Comment by cosimoNigro** [comment]
The [notebook](https://agnpy.readthedocs.io/en/latest/tutorials/ssc_sherpa_fit.html) added in the new docs.

**Comment by cosimoNigro** [comment]
It's been a while that we have proper examples for fitting, so I am closing this.
