### ISSUE TITLE
absorption (DT) for gamma rays moving with an angle to the jet axis

### ISSUE THREAD

**Issue by jsitarek** [cosimoNigro/agnpy#80]
HI @cosimoNigro 

I had a look into implementing a proper calculations of the absorption for a case of mu_s != 1 (moving at an angle to the jet axis)
I want to test is carefully because there is a lot of fun with geometry, and different "phi" angles, but you can have a look at the current code in this branch if you have any comments about the code structure:
https://github.com/jsitarek/agnpy/tree/absorption_mu_s_dependent

the idea for the code would be to leave the current absorption functions (we might remove the mu_s parameter from them, and also avoid "phi" integrals later on), and add new functions with ..._mu_s in the name that would calculate the more complicated integrals with those proper direction.
I think this can be also a very nice addition to the paper, I could write the corresponding formulas in a dedicated appendix.

attached below some results from comparing absorption at mu_s=1, with the current code (that we know that is buggy) and this new code. qualitatively it makes sense, but I want to have a look 
if I can make also some quantitative checks. 

![abs_dt_r_0 1_mu_s_0 9](https://user-images.githubusercontent.com/33022433/108382062-b82a0b00-7208-11eb-93e8-d043a7af0c59.png)
![abs_dt_r_3 1_mu_s_0 9](https://user-images.githubusercontent.com/33022433/108382059-b82a0b00-7208-11eb-963a-fa55423b95d5.png)
![abs_dt_r_3 1_mu_s_0 99](https://user-images.githubusercontent.com/33022433/108382056-b7917480-7208-11eb-9423-20a093394f05.png)
![abs_dt_r_3 1_mu_s_0 999](https://user-images.githubusercontent.com/33022433/108382439-1fe05600-7209-11eb-9e0b-20e59b371b51.png)

**Comment by jsitarek** [comment]
Hi @cosimoNigro I'm happy enough with the code to make a PR #81

**Comment by cosimoNigro** [comment]
Hi @jsitarek,

please remember to provide some formulas explaining the newly added calculations, especially since they are not available in any other reference.

**Comment by jsitarek** [comment]
[absorption_mu_s.pdf](https://github.com/cosimoNigro/agnpy/files/6029677/absorption_mu_s.pdf)
[absorption_mu_s.txt](https://github.com/cosimoNigro/agnpy/files/6029682/absorption_mu_s.txt)
here it is please let me know if it is fine or do you need anything more.
While preparing this I realized that I wrote something wrong in the code, i.e. I set phi=0 for point source thinking that it does not matter due to symmetry, however this is not true because when the gamma ray propagates this original symmetry disappears, however the true value is indeed 0 :-), so only the comment was wrong, I will make a small PR to fix it

after this, I think this issue can be closed (please let me know if you want to keep it open)
