### ISSUE TITLE
making 0.1.0?

### ISSUE THREAD

**Issue by cosimoNigro** [cosimoNigro/agnpy#93]
If we were to follow the `major.minor.patch` schema, it's been a while we are just "patching" `agnpy` :grin:. 
I think we have gathered a set of stable and cross-checked features and we can step-up to our first "minor" release.

What do you think @jsitarek?  

Two things I would like to add to our first minor release:
- a [citation.cff](https://citation-file-format.github.io/) giving instructions on how to properly cite the software;
- a `.zenodo.json` file to directly produce the information displayed in the zenodo page (summary, authors, keywords, etc... - now I am adding them manually each time). I have found plenty of examples in `github` but [no clear instructions on how to actually generate this file](https://github.com/zenodo/zenodo/issues/1606), I will give it a try...

**Comment by jsitarek** [comment]
Hi @cosimoNigro 
sorry for a late feedback on this. 
while we still have some issues to understand, indeed most of the code is very well tested and stable, so I fully support making 0.1.0

**Comment by cosimoNigro** [comment]
Made our first minor release!
